import type { Metadata } from "next";
import "./globals.css";

import { Nunito } from '@next/font/google';

const nunito = Nunito({
  subsets: ['latin'],
  weight: '200', // ExtraLight corresponde ao peso 200
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { AppSidebar } from "@/components/app-sidebar"
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"
import { Separator } from "@/components/ui/separator"
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"
import { AlertProvider } from "@/hooks/use-alert";
import { GlobalAlert } from "@/components/Alert";
import { BreadcrumbDynamic } from "@/components/Breadcrumb";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${nunito.className} antialiased`}
      >
        <AlertProvider>
          <GlobalAlert />
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <header className="flex h-16 shrink-0 items-center gap-2 text-text">
                <div className="flex items-center gap-2 px-4">
                  <SidebarTrigger className="-ml-1" />
                  <Separator orientation="vertical" className="mr-2 h-4" />
                  <BreadcrumbDynamic />
                </div>
              </header>
              <div className="w-full h-[calc(100vh-84px)]">
                {children}
              </div>
            </SidebarInset>
          </SidebarProvider>
        </AlertProvider>
      </body>
    </html>
  )
}
