import type { Metadata } from "next";
import "./globals.css";

import { Analytics } from "@vercel/analytics/react"

import { Nunito } from '@next/font/google';

const nunito = Nunito({
  subsets: ['latin'],
  weight: '200', // ExtraLight corresponde ao peso 200
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${nunito.className} antialiased`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  )
}
